CXX = clang++
CXXFLAGS = -std=c++17 -fopenmp -O3 -I/Users/maoyachen/.micromamba/envs/gnuradio/include
LDFLAGS = -L/Users/maoyachen/.micromamba/envs/gnuradio/lib \
	-Wl,-rpath,/Users/maoyachen/.micromamba/envs/gnuradio/lib \
	-lgnuradio-runtime \
	-lgnuradio-analog \
	-lgnuradio-blocks \
	-lgnuradio-digital \
	-lgnuradio-pmt \
	-lspdlog \
	-lfmt
