CXX = /usr/local/opt/llvm/bin/clang++
CXXFLAGS = -std=c++17 -O2 -I/Users/maoyachen/.micromamba/envs/gnuradio/include
LDFLAGS = -fopenmp -L/Users/maoyachen/.micromamba/envs/gnuradio/lib \
	-Wl,-rpath,/Users/maoyachen/.micromamba/envs/gnuradio/lib \
	-lgnuradio-runtime \
	-lgnuradio-analog \
	-lgnuradio-blocks \
	-lgnuradio-digital \
	-lgnuradio-pmt \
	-lspdlog \
	-lfmt
